export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  // FILTERED_PRODUCTS: "FILTERED_PRODUCTS"
  MENS_CLOTH: "MENS_CLOTH",
  WOMENS_CLOTH: "WOMEN_CLOTH",
  ELECTRONICS: "ELECTRONICS",
  JEWELERY: "JEWELRY"
};
